---
galaxy_info:
  author: ShaddGallegos
  description: Ansible role for Red Hat Satellite 6.17 server installation and configuration
  company: Red Hat
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  platforms:
    - name: EL
      versions:
        - "9"
  galaxy_tags:
    - satellite
    - redhat
    - infrastructure
    - automation

dependencies: []

collections:
  - community.general
  - ansible.posix
  - redhat.satellite
  - theforeman.foreman
