---
# Handlers for satellite_pxe_services role

- name: restart dhcpd
  ansible.builtin.systemd:
    name: dhcpd
    state: restarted
  become: true

- name: restart tftp
  ansible.builtin.systemd:
    name: tftp.socket
    state: restarted
  become: true

- name: restart libvirtd
  ansible.builtin.systemd:
    name: libvirtd
    state: restarted
  become: true

- name: reload firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded
  become: true
