---
# Post-installation configuration tasks

- name: Enable provisioning for libvirt
  ansible.builtin.user:
    name: foreman
    groups: libvirt
    append: true
  become: true

- name: Generate SSH key for foreman-proxy
  ansible.builtin.user:
    name: foreman-proxy
    generate_ssh_key: true
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  become: true

- name: Set ownership for foreman-proxy SSH keys
  ansible.builtin.file:
    path: /usr/share/foreman-proxy/.ssh
    owner: foreman-proxy
    group: foreman-proxy
    state: directory
  become: true

- name: Set ownership for foreman-proxy SSH key files
  ansible.builtin.file:
    path: "{{ item }}"
    owner: foreman-proxy
    group: foreman-proxy
    mode: '0600'
  loop:
    - /usr/share/foreman-proxy/.ssh/id_rsa
    - /usr/share/foreman-proxy/.ssh/id_rsa.pub
  become: true
  ignore_errors: true

- name: Enable IP forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true
  become: true

- name: Set kernel domainname
  ansible.builtin.shell: echo "{{ satellite_hostname.split('.')[1:] | join('.') }}" > /proc/sys/kernel/domainname
  become: true
  changed_when: false

- name: Configure hammer admin user
  ansible.builtin.template:
    src: hammer_config.yml.j2
    dest: /root/.hammer/cli.modules.d/foreman.yml
    mode: '0600'
  become: true

- name: Test hammer connectivity
  ansible.builtin.command: hammer ping
  become: true
  register: hammer_test
  ignore_errors: true

- name: Display hammer connectivity status
  ansible.builtin.debug:
    msg: "Hammer connectivity: {{ 'OK' if hammer_test.rc == 0 else 'Failed' }}"
