---
# Satellite installation tasks

- name: Enable required RHEL 9 and Satellite repositories
  ansible.builtin.shell: |
    subscription-manager repos --enable=rhel-9-for-x86_64-baseos-rpms
    subscription-manager repos --enable=rhel-9-for-x86_64-appstream-rpms
    subscription-manager repos --enable=satellite-6.17-for-rhel-9-x86_64-rpms
    subscription-manager repos --enable=satellite-maintenance-6.17-for-rhel-9-x86_64-rpms
  become: true
  ignore_errors: true

- name: Ensure fapolicyd is started and enabled
  ansible.builtin.systemd:
    name: fapolicyd
    state: started
    enabled: true
  become: true

- name: Register system with Red Hat Insights
  ansible.builtin.command: insights-client --register
  become: true
  ignore_errors: true

- name: Set Insights display name to proper hostname
  ansible.builtin.lineinfile:
    path: /etc/insights-client/insights-client.conf
    regexp: '^#?display_name='
    line: 'display_name={{ insights_display_name }}'
  become: true
  when: configure_insights | bool

- name: Re-register with Insights using correct hostname
  ansible.builtin.command: insights-client --register --display-name={{ insights_display_name }}
  become: true
  ignore_errors: true
  when: configure_insights | bool

- name: Run satellite-installer with required options
  ansible.builtin.command: >
    satellite-installer --scenario satellite
    --foreman-initial-admin-username {{ satellite_admin_user }}
    --foreman-initial-admin-password {{ satellite_config_vars.admin_password | default('changeme') }}
    --foreman-proxy-dhcp true
    --foreman-proxy-dns true
    --foreman-proxy-tftp true
  become: true
  register: satellite_install_result
  notify: restart satellite services

- name: Display satellite installation result
  ansible.builtin.debug:
    msg: "Satellite installation {{ 'completed successfully' if satellite_install_result.rc == 0 else 'completed with warnings' }}"
