---
# System preparation tasks

- name: Set Satellite hostname
  ansible.builtin.hostname:
    name: "{{ satellite_hostname }}"
  become: true

- name: Install required OS packages
  ansible.builtin.dnf:
    name:
      - chrony
      - firewalld
      - policycoreutils-python-utils
      - wget
      - curl
    state: present
  become: true

- name: Update all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
  become: true

- name: Set SELinux mode
  ansible.posix.selinux:
    policy: targeted
    state: enforcing
  become: true

- name: Set system locale
  ansible.builtin.command: localectl set-locale LANG=en_US.UTF-8
  become: true
  changed_when: false

- name: Enable and start chronyd
  ansible.builtin.systemd:
    name: chronyd
    state: started
    enabled: true
  become: true

- name: Unlock packages for additional installations
  ansible.builtin.command: foreman-maintain packages unlock
  become: true
  ignore_errors: true
  when: unlock_packages | bool

- name: Install python3-pip for additional Python packages
  ansible.builtin.dnf:
    name: python3-pip
    state: present
  become: true
  when: install_python_deps | bool

- name: Upgrade pip and install essential Python packages
  ansible.builtin.shell: pip3 install --upgrade pip setuptools wheel netaddr
  become: true
  ignore_errors: true
  when: install_python_deps | bool

- name: Lock packages back after installations
  ansible.builtin.command: foreman-maintain packages lock
  become: true
  ignore_errors: true
  when: unlock_packages | bool
