---
# User setup tasks

- name: Create admin user
  ansible.builtin.user:
    name: "{{ satellite_config_vars.admin_user | default('admin') }}"
    password: "{{ satellite_config_vars.admin_password | default('admin123') | password_hash('sha512') }}"
    shell: /bin/bash
    createhome: true
    groups: wheel
    append: true
  become: true

- name: Add admin to sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: "{{ satellite_config_vars.admin_user | default('admin') }} ALL=(ALL) NOPASSWD: ALL"
    validate: visudo -cf %s
  become: true

- name: Ensure SSH keys for root
  ansible.builtin.user:
    name: root
    generate_ssh_key: true
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  become: true

- name: Ensure admin user has passwordless sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/{{ satellite_config_vars.admin_user | default('admin') }}
    line: "{{ satellite_config_vars.admin_user | default('admin') }} ALL=(ALL) NOPASSWD: ALL"
    create: true
    mode: '0440'
    validate: visudo -cf %s
  become: true

- name: Ensure SSH keys for admin
  ansible.builtin.user:
    name: "{{ satellite_config_vars.admin_user | default('admin') }}"
    generate_ssh_key: true
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  become: true
