---
# Playbook: 05_create_lifecycle_environments.yml  
# Purpose: Create lifecycle environments for RHEL 8, 9, and 10
# URL Reference: https://satellite.prod.spg/lifecycle_environments

- name: "[STEP 5] Create Lifecycle Environments"
  block:
    - name: "[VALIDATION] Confirm lifecycle environment creation"
      fail:
        msg: "Lifecycle environment creation cancelled by user"
      when: confirm_lifecycle_envs != "yes"

    - name: "[INFO] Creating lifecycle environments"
      debug:
        msg: "Creating lifecycle environments for RHEL 8, 9, and 10 (including composite environments)"

    # RHEL 8 Environments
    - name: "[RHEL 8] Create RHEL 8 lifecycle environments"
      theforeman.foreman.lifecycle_environment:
        server_url: "{{ satellite_server_url }}"
        username: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        organization: "{{ satellite_organization }}"
        name: "{{ item.name }}"
        prior: "{{ item.prior }}"
        description: "{{ item.description }}"
        state: present
      loop: "{{ lifecycle_environments.rhel8 }}"
      loop_control:
        label: "Creating: {{ item.name }}"
      register: rhel8_env_results

    # RHEL 9 Environments (including composite)
    - name: "[RHEL 9] Create RHEL 9 lifecycle environments"
      theforeman.foreman.lifecycle_environment:
        server_url: "{{ satellite_server_url }}"
        username: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        organization: "{{ satellite_organization }}"
        name: "{{ item.name }}"
        prior: "{{ item.prior }}"
        description: "{{ item.description }}"
        state: present
      loop: "{{ lifecycle_environments.rhel9 }}"
      loop_control:
        label: "Creating: {{ item.name }}"
      register: rhel9_env_results

    # RHEL 10 Environments
    - name: "[RHEL 10] Create RHEL 10 lifecycle environments"
      theforeman.foreman.lifecycle_environment:
        server_url: "{{ satellite_server_url }}"
        username: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        organization: "{{ satellite_organization }}"
        name: "{{ item.name }}"
        prior: "{{ item.prior }}"
        description: "{{ item.description }}"
        state: present
      loop: "{{ lifecycle_environments.rhel10 }}"
      loop_control:
        label: "Creating: {{ item.name }}"
      register: rhel10_env_results

    - name: "[VERIFICATION] Verify all lifecycle environments were created"
      uri:
        url: "{{ satellite_server_url }}/katello/api/v2/environments"
        method: GET
        user: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        force_basic_auth: true
        validate_certs: false
        status_code: 200
      register: all_environments

    - name: "[FILTER] Filter newly created environments"
      set_fact:
        created_environments: "{{ all_environments.json.results | selectattr('name', 'match', 'RHEL_(8|9|10)_(DEV|TEST|PROD)_x86_64.*') | list }}"

    - name: "[DISPLAY] Show created environments"
      debug:
        msg: |
          Environment: {{ item.name }}
          Label: {{ item.label }}
          Prior: {{ item.prior.name if item.prior else 'Library' }}
          ID: {{ item.id }}
      loop: "{{ created_environments }}"
      loop_control:
        label: "{{ item.name }}"

    - name: "[SUMMARY] Lifecycle environment creation summary"
      debug:
        msg: |
          [COMPLETE] Lifecycle environments created successfully
          - RHEL 8 Environments: {{ rhel8_env_results.results | selectattr('failed', 'equalto', false) | list | length }}
          - RHEL 9 Environments: {{ rhel9_env_results.results | selectattr('failed', 'equalto', false) | list | length }}
          - RHEL 10 Environments: {{ rhel10_env_results.results | selectattr('failed', 'equalto', false) | list | length }}
          - Total Environments Created: {{ created_environments | length }}

    - name: "[VALIDATION] Verify environment path structure"
      debug:
        msg: |
          [RHEL 8 PATH] Library -> RHEL_8_DEV_x86_64 -> RHEL_8_TEST_x86_64 -> RHEL_8_PROD_x86_64
          [RHEL 9 PATH] Library -> RHEL_9_DEV_x86_64 -> RHEL_9_TEST_x86_64 -> RHEL_9_PROD_x86_64
          [RHEL 9 COMPOSITE] Library -> RHEL_9_DEV_x86_64-Composit -> RHEL_9_TEST_x86_64-Composit -> RHEL_9_PROD_x86_64-Composit
          [RHEL 10 PATH] Library -> RHEL_10_DEV_x86_64 -> RHEL_10_TEST_x86_64 -> RHEL_10_PROD_x86_64

    - name: "[NEXT] Next steps"
      debug:
        msg: |
          [NEXT STEP] Create content views:
          ansible-playbook 06_create_content_views.yml
          [RHEL 9 COMPOSITE] Library -> RHEL_9_DEV_x86_64-Composit -> RHEL_9_TEST_x86_64-Composit -> RHEL_9_PROD_x86_64-Composit
          [RHEL 10 PATH] Library -> RHEL_10_DEV_x86_64 -> RHEL_10_TEST_x86_64 -> RHEL_10_PROD_x86_64

    - name: "[NEXT] Next steps"
      debug:
        msg: |
          [NEXT STEP] Create content views:
          ansible-playbook 06_create_content_views.yml
