---
# Enable Red Hat repositories required for Satellite

- name: Enable Red Hat repositories
  community.general.rhsm_repository:
    name: "{{ item }}"
    state: enabled
  loop:
    - "rhel-{{ ansible_distribution_major_version }}-for-x86_64-baseos-rpms"
    - "rhel-{{ ansible_distribution_major_version }}-for-x86_64-appstream-rpms"
    - "satellite-6.17-for-rhel-{{ ansible_distribution_major_version }}-x86_64-rpms"
    - "satellite-maintenance-6.17-for-rhel-{{ ansible_distribution_major_version }}-x86_64-rpms"
  register: repo_enable_result
  retries: 3
  delay: 5
  until: repo_enable_result is succeeded

- name: Verify enabled repositories
  ansible.builtin.command:
    cmd: subscription-manager repos --list-enabled
  register: enabled_repos
  changed_when: false

- name: Display enabled repositories
  ansible.builtin.debug:
    msg: "Repository enablement completed successfully"
