---
# Task File: publish_content_views.yml
# Purpose: Publish content views to make them available for activation keys

- name: "[INFO] Publishing content views"
  debug:
    msg: "Publishing content views to make them available for activation keys"

- name: "[SET DEFAULT] Set default content views to publish"
  set_fact:
    content_views_to_publish:
      - name: "RHEL8-CV"
        description: "RHEL 8 Content View"
      - name: "RHEL9-CV"
        description: "RHEL 9 Content View"
      - name: "RHEL10-CV"
        description: "RHEL 10 Content View"
  when: content_views_to_publish is not defined

- name: "[PUBLISH] Publish initial version of content views"
  theforeman.foreman.content_view_version:
    server_url: "{{ satellite_server_url }}"
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    organization: "{{ satellite_organization | default('Default Organization') }}"
    content_view: "{{ item.name }}"
    description: "Initial version of {{ item.description }}"
    state: present
  loop: "{{ content_views_to_publish }}"
  register: content_view_publish_result
  tags: publish_content_views

- name: "[WAIT] Wait for content view publishing to complete"
  pause:
    seconds: 10
    prompt: "Waiting for content view publishing to complete..."

- name: "[DISPLAY] Show published content views"
  debug:
    msg:
      - "✓ Content View Published: {{ item.item.name }}"
      - "  Description: {{ item.item.description }}"
      - "  Status: Published to Library environment"
  loop: "{{ content_view_publish_result.results }}"
  when: item.changed or not item.failed | default(false)
  tags: publish_content_views

- name: "[INFO] Content view publishing completed"
  debug:
    msg: "Content views have been published and are now available for activation keys"
