---
# Node Provisioning Workflow
# Purpose: Provision nodes using the configured Satellite server
# Usage: ansible-playbook -i inventory node_provisioning_workflow.yml

- name: "Satellite Node Provisioning Workflow"
  hosts: satellite_servers
  gather_facts: true
  vars:
    # Node Configuration
    provision_nodes:
      - name: "web01"
        hostgroup: "Web-Servers"
        compute_profile: "2-Medium-Node"
        activation_key: "RHEL9-AK"
        cpus: 2
        memory_gb: 4
        disk_gb: 50
      - name: "db01"
        hostgroup: "Database-Servers"
        compute_profile: "3-Large-Node"
        activation_key: "RHEL9-AK"
        cpus: 4
        memory_gb: 8
        disk_gb: 100
      - name: "app01"
        hostgroup: "Application-Servers"
        compute_profile: "2-Medium-Node"
        activation_key: "RHEL9-AK"
        cpus: 2
        memory_gb: 4
        disk_gb: 75

  tasks:
    - name: Include node provisioning role
      ansible.builtin.include_role:
        name: satellite_provisioning
      vars:
        nodes_to_provision: "{{ provision_nodes }}"

    - name: Display provisioning summary
      ansible.builtin.debug:
        msg: |
          🎯 NODE PROVISIONING WORKFLOW COMPLETE
          ======================================
          
          📊 Provisioned Nodes:
          {% for node in provision_nodes %}
          • {{ node.name }}: {{ node.compute_profile }} ({{ node.cpus }}vCPU, {{ node.memory_gb }}GB RAM)
          {% endfor %}
          
          🚀 All nodes are being provisioned via Satellite PXE services!
