---
# Individual Role Testing Playbook
# Purpose: Test individual Satellite roles independently
# Usage: ansible-playbook -i inventory test_individual_roles.yml --tags role_name

- name: "Test Individual Satellite Roles"
  hosts: satellite_servers
  gather_facts: true
  become: true

  tasks:
    - name: "Test Satellite Build Role"
      ansible.builtin.include_role:
        name: satellite_build
      tags: ['test_build', 'satellite_build']

    - name: "Test PXE Services Role"
      ansible.builtin.include_role:
        name: satellite_pxe_services
      tags: ['test_pxe', 'satellite_pxe_services']

    - name: "Test Content Role"
      ansible.builtin.include_role:
        name: satellite_content
      tags: ['test_content', 'satellite_content']

    - name: Display test results
      ansible.builtin.debug:
        msg: |
          🧪 SATELLITE ROLES TESTING COMPLETE
          ====================================
          
          ✅ Available roles tested:
          • satellite_build: Core Satellite installation
          • satellite_pxe_services: PXE and LibVirt services
          • satellite_content: Repository and content management
          
          💡 Usage Examples:
          # Test only build role:
          ansible-playbook test_individual_roles.yml --tags satellite_build
          
          # Test only PXE services:
          ansible-playbook test_individual_roles.yml --tags satellite_pxe_services
          
          # Test only content configuration:
          ansible-playbook test_individual_roles.yml --tags satellite_content
      tags: ['summary']
